# => Build container
ARG base=ipbm-base-ui:latest
FROM $base as builder

RUN yarn build

# => Run container
FROM nginx:1.15.2-alpine

# Nginx config
RUN rm -rf /etc/nginx/conf.d
COPY ui/apps/ipbm-ui/conf /etc/nginx

# Static build
COPY --from=builder /ui/apps/ipbm-ui/build /usr/share/nginx/html/

# Default port exposure
EXPOSE 80

# Copy .env file and shell script to container
WORKDIR /usr/share/nginx/html
COPY ui/apps/ipbm-ui/env.sh .
COPY ui/apps/ipbm-ui/.env .

# Add bash
RUN apk add --no-cache bash

# Make our shell script executable
RUN chmod +x env.sh

# Start Nginx server
CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""]